### ISSUE TITLE
viscoelastic2 and source type 50

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#293]
**Describe the bug**
model run with viscoelastic2 and source type 50 crashes with mapping point sources to LTS cells.
Do not crash without point source.
Do not crash with elasticity.

```
Fri Feb 12 21:19:07, Info:  Mapping point sources to LTS cells...

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 2157580 RUNNING AT i01r01c02s05
=   KILLED BY SIGNAL: 11 (Segmentation fault)
```

**Expected behavior**
do not crash

**To Reproduce**
supermucNG, master branch, e3b47a281dbf97729f4d43928ffdea071f0dd276
setup here: /hppfs/work/pr45fi/di73yeq4/model3

**Comment by sebwolf-de** [comment]
I looked a bit around: The error also occurs with a simple small LOH3 setup.
On SuperMUC-NG I get the problem with intel and gcc, when I wanted to have a closer look on my local machine with gcc, the bug did not occur.

**Comment by sebwolf-de** [comment]
https://github.com/SeisSol/SeisSol/blob/master/src/SourceTerm/PointSource.cpp#L111-L113
Can you comment out these lines? Should fix the problem.

**Comment by sebwolf-de** [comment]
Hi @Thomas-Ulrich I found the bug, fixed it. Can you check the branch if you setup now works?

**Comment by Thomas-Ulrich** [comment]
It works also on the Nepal setup, thx!

**Comment by AliceGabriel** [comment]
Fantastic, thank you!

**Comment by Thomas-Ulrich** [comment]
Hi,
It turns out that I forgot to uncomment the source when testing again... And the error is still there, sorry about that:
```
Rank:        0 | Info    | Synchronizing copy cell material data.
Mon Mar 01 10:27:20, Info:  <---------------------------------------------------------> 
Mon Mar 01 10:27:20, Info:  <                      Point sources                      > 
Mon Mar 01 10:27:20, Info:  <---------------------------------------------------------> 
Mon Mar 01 10:27:20, Info:  Finding meshIds for point sources... 
Mon Mar 01 10:27:20, Info:  Cleaning possible double occurring point sources for MPI... 
Mon Mar 01 10:27:20, Info:  Mapping point sources to LTS cells... 
Mon Mar 01 10:27:20, Info:  .. finished point source initialization. 
Rank:        0 | Info    | Initializing element local matrices.

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 12 PID 2686731 RUNNING AT i01r01c01s08
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================
```

**Comment by sebwolf-de** [comment]
Okay, so I've checked again. The bug only appears when built with intel. Can you try again with gcc?

**Comment by Thomas-Ulrich** [comment]
Hi,
I confirm it works (but the code is extremely slow, I will open another issue).

**Comment by sebwolf-de** [comment]
Okay, I am closing this issue.

**Comment by Thomas-Ulrich** [comment]
you mean I should open a new issue:
`viscoelastic2 and source type 50 not working with intel compilers`?
I don't understand why you close the issue.

**Comment by sebwolf-de** [comment]
Sorry for being too short here.
I've tested the source type 50 with viscoelasticity on a small mesh with LOH3, it worked.
I've tested the Nepal setup with source type 50 (`parameters.par`) and elasticity, it worked.
I've tested the Nepal setup with viscoelasticity, at first it didn't work, since it required too much memory on the one node. Then I changed to O3, then it worked.

**Comment by Thomas-Ulrich** [comment]
you mean, with intel?
I m running it on 16 nodes and o4, there should be enough memory, right?
So you think intel needs more memory than gcc, and therefore the program 
crashes?

**Comment by sebwolf-de** [comment]
Yes, I've built it with intel, Release_dskx_3_viscoelastic2, and ran it in an interactive session on one node.

**Comment by Thomas-Ulrich** [comment]
it is not a memory issue. I can run the same mesh with attenuation if I use a source type 42.

**Comment by sebwolf-de** [comment]
Hi, I checked again and it works i.e. I see 
```
Fri Mar 05 16:11:49, Info:  Writing free surface at time 0.
Fri Mar 05 16:11:49, Info:  Writing free surface at time 0. Done.
Fri Mar 05 16:11:49, Info:  #max-updates since sync:  0  @  0
```
What have I done:
```
> git checkout master # i.e. 98d3933b
> module list -t
admin/1.0
tempdir/1.0
lrz/1.0
intel/19.0
mkl/2019
mpi.intel/2019
itac/2019
advisor_xe/2019
amplifier_xe/2019
inspector_xe/2019
devEnv/Intel/2019
spack/release/19.2
cmake/3.14.4
python/3.6_intel
slurm_setup/1.0
libszip/2.1.1
parmetis/4.0.3-intel-impi-i64-r64
metis/5.1.0-intel-i64-r64
numactl/2.0.11
hdf5/1.8.20-intel-impi-frt-threadsafe
netcdf/4.6.1-intel-impi-hdf5v1.8-parallel
gcc/9
neovim/0.3.1
lrztools/2.0
>  cmake .. -DORDER=6 -DTESTING=OFF -DEQUATIONS=viscoelastic2 -DNUMBER_OF_MECHANISMS=3 -DHOST_ARCH=skx
> make -j48
```
I launched the `model3/parameters.par` you provided on 17 nodes, which timed out after some time (I have set the job time to 1min), but for sure the computations started.

**Comment by Thomas-Ulrich** [comment]
I think if you do that, I assume you compile with gcc:
```
di73yeq4@login01:/hppfs/work/pr45fi/di73yeq4/SeisSol/build-release2> cmake .. -DORDER=6 -DTESTING=OFF -DEQUATIONS=viscoelastic2 -DNUMBER_OF_MECHANISMS=3 -DHOST_ARCH=skx
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- The Fortran compiler identification is GNU 4.8.5
```
And therefore the code is slow and it times out. (I mean we know that it works with gcc)
or did you have the mpiwrapper set in your ~/.bashrc?
Could you try running on the test queue with
ReceiverOutputInterval = 0.1
To see how long it takes to get to 0.1s (or if you can reproduce my bug)?

Thomas.

**Comment by sebwolf-de** [comment]
Indeed I have set the wrappers: `The C compiler identification is Intel 19.0.5.20190815`

**Comment by sebwolf-de** [comment]
```
Fri Mar 05 16:57:34, Info:  Writing free surface at time 0.
Fri Mar 05 16:57:34, Info:  Writing free surface at time 0. Done.
Fri Mar 05 16:57:34, Info:  #max-updates since sync:  0  @  0
Fri Mar 05 16:58:11, Info:  Writing free surface at time 0.2.
Fri Mar 05 16:58:11, Info:  Writing free surface at time 0.2. Done.
Fri Mar 05 16:58:11, Info:  1013.53 GFLOPS on rank 0
```

**Comment by Thomas-Ulrich** [comment]
this one is on 16 nodes?
I doubt that lrztools and slurm_setup could make a difference, right?

**Comment by sebwolf-de** [comment]
This is on 17 nodes, since the general queue has a smaller queue in general ;-)
lrztools shouldn't make a difference, that's just convenience tools. slurm_setup shouldn't make a difference neither. But you can just load them to make sure ;-)
Did you try to build in an empty directory? If not, cmake sometimes keeps links to recently used libraries, which you might don't want to use actually.

**Comment by Thomas-Ulrich** [comment]
it's working!!!! Ok, let me double-check a few things before closing...

**Comment by Thomas-Ulrich** [comment]
Ok maybe there was something with the cmake cache, sorry for your time, and thank you for your help!

**Comment by sebwolf-de** [comment]
Always happy to help

**Comment by krenzland** [comment]
> Ok maybe there was something with the cmake cache, sorry for your time, and thank you for your help!

I think you need to delete the cache when changing compilers.
If you're using an out-of-source build, just rm -rf * when you change the environment (e.g. loaded modules, compilers, etc) to make sure.
