### ISSUE TITLE
Error while loading the mesh

### ISSUE THREAD

**Issue by fvella** [SeisSol/SeisSol#37]
I follow the instructions. When I run the executable:

```./SeisSol_release_generatedKernels_snoarch_hybrid_none_9_6 parameters_tpv33.par```

 I got 

```
Rank:        0 | Error   | invalid line in namelist MeshNml: MeshFile = tpv33_gmsh.32         ! Name of mesh file
```

Here my files: 

```
DGPATH  parameters_tpv33_easi.par  SeisSol_release_generatedKernels_dsnb_hybrid_none_9_6     tpv33_faultreceivers.dat  tpv33_gmsh.xdmf            tpv33_material.yaml
output  parameters_tpv33.par       SeisSol_release_generatedKernels_snoarch_hybrid_none_9_6  tpv33_gmsh                tpv33_initial_stress.yaml  tpv33_receivers.dat

```

**Comment by swollherr** [comment]
We recently updated to a new mesh format (PUML) which is already included as a comment in the parameter file.
The linked parameter file still calls the netcdf file which we don't provide anymore.

You can either uncomment line 53 and 54 and comment line 55 and 56 in the parameter file or update your example folder with the version that I just committed.

Please don't forget to compile SeisSol with the options:
metis = 'yes'
metisDir = '$folder_to_metis'
as described here: https://github.com/SeisSol/SeisSol/wiki/Compilation#f-compiling-seissol

**Comment by fvella** [comment]
At the moment I have a problem, hopefully stupid,  with scons when it tries to detect ParMetis. 
Then, I will check your solution. 
Thanks.

**Comment by fvella** [comment]
I still have the problem:

```
./SeisSol parameters_tpv33.par
```

My parameters_tpv33.par file containts at lines 53-57
```
&MeshNml
MeshFile = tpv33_gmsh         ! Name of mesh file
meshgenerator = PUML          ! Name of meshgenerator (format)
!MeshFile = tpv33_gmsh.32     ! Name of mesh file
!meshgenerator = Netcdf       ! Name of meshgenerator (format)
/

```

Directory contains:
```
DGPATH                     parameters_tpv33.par  stderr.log  tpv33_faultreceivers.dat  tpv33_gmsh.xdmf            tpv33_material.yaml
parameters_tpv33_easi.par  SeisSol               stdout.log  tpv33_gmsh                tpv33_initial_stress.yaml  tpv33_receivers.dat

```

**Comment by Thomas-Ulrich** [comment]
Hi,
I cannot really understand why you get an error but I can comment on the error.
Basically, Seissol reads the Nml MeshNml in your parameter file, and his unable to interpret something in it. So the error is not while loading the mesh, it is when reading the mesh filename and the mesh type in the parameter file. This being said, It is very strange. 
With intel compiler, writing MeshFile = tpv33_gmsh or MeshFile = 'tpv33_gmsh' does not make a difference, but maybe it is different with gfortran (if you do not use intel compilers)?
Could you try that?

Thomas.

**Comment by fvella** [comment]
Maybe the mesh file is corrupted? 
I am downloading via 

```
wget https://syncandshare.lrz.de/dl/fi72mQiszp6vSs7qN8tdZJf9/tpv33_gmsh
wget https://syncandshare.lrz.de/dl/fiEi52Xiwwqkf2sNpTrCHjhw/tpv33_gmsh.xdmf
```

**Comment by Thomas-Ulrich** [comment]
Hi, 
I ve run this small program with gfortran and ifort:

```fortran
program test
INTEGER :: readStat
INTEGER                          :: periodic
REAL                             :: ScalingMatrixX(3), ScalingMatrixY(3), ScalingMatrixZ(3), &
                                displacement(3)
CHARACTER(LEN=600) :: MeshFile, meshgenerator
NAMELIST                         /MeshNml/ MeshFile, meshgenerator, periodic, &
                                    periodic_direction, displacement, ScalingMatrixX, &
ScalingMatrixY, ScalingMatrixZ
OPEN(UNIT=1,FILE='test.par')
READ(1, IOSTAT=readStat, nml = MeshNml)
print *,readStat, MeshFile
end program test
```

with gfortran (and the quotes around the filename) it returns:
        5010 tpv33_gmsh
with ifort:
           0 
 tpv33_gmsh 

As 5010<>0, it returns an error. This might help finding a fix.

**Comment by Thomas-Ulrich** [comment]
Hi,
the problem is in my opinion related with the absence of '' around the mesh file in the parameter file. It is possible with ifort but not with gfortran. Then you should update all other strings in the parameter file (e.g. PUML to 'PUML'). We will update the file.

Thomas.
